package com.ecommerce.product.dto;



import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class ProductRequest {
    private String name;
    private String description;
    private BigDecimal price;
    private Integer quantity;
    private String category;
    private String imageUrl;
    
    // NO id - auto-generated by system
    // NO active - default is true (hardcoded in entity)
    // NO createdAt, updatedAt - auto-managed
}