package com.ecommerce.user.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class UserRequest {
    private String firstName;
    private String lastName;
    private String email;
    private String phone;
    private AddressDTO address;
    
    // NO id - auto-generated by system
    // NO role - auto-assigned (default: CUSTOMER)
    // NO createdAt, updatedAt - auto-managed
}